trigger:
  branches:
    include: [ '*' ]
    exclude: [ 'refs/tags/*' ]

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: Build and test
  inputs:
    targetType: filePath
    filePath: ./build.ps1
  env:
    CODECOV_TOKEN: $(CODECOV_TOKEN)

- task: PublishTestResults@2
  displayName: Publish test results (net472)
  inputs:
    testRunTitle: net472
    testResultsFormat: VSTest
    testResultsFiles: artifacts\Test results\net472.trx

- task: PublishTestResults@2
  displayName: Publish test results (netcoreapp2.1)
  inputs:
    testRunTitle: netcoreapp2.1
    testResultsFormat: VSTest
    testResultsFiles: artifacts\Test results\netcoreapp2.1.trx

- task: PublishTestResults@2
  displayName: Publish test results (netcoreapp3.0)
  inputs:
    testRunTitle: netcoreapp3.0
    testResultsFormat: VSTest
    testResultsFiles: artifacts\Test results\netcoreapp3.0.trx

- task: PublishTestResults@2
  displayName: Publish test results (netcoreapp3.1)
  inputs:
    testRunTitle: netcoreapp3.1
    testResultsFormat: VSTest
    testResultsFiles: artifacts\Test results\netcoreapp3.1.trx

- task: PublishBuildArtifacts@1
  displayName: Publish test results artifact
  inputs:
    PathtoPublish: artifacts\Test results
    ArtifactName: Test results

- task: PublishBuildArtifacts@1
  displayName: Publish NuGet package artifact
  inputs:
    PathtoPublish: artifacts\Packages
    ArtifactName: NuGet package

- task: NuGetCommand@2
  displayName: Publish to MyGet
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  inputs:
    command: push
    packagesToPush: 'artifacts\Packages\*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: MyGet
